### ISSUE TITLE
Cannot find model/test

### ISSUE THREAD

**Issue by JackieZhuzzz** [zhaofuq/LOD-Web-Viewer#1]
Hi, 

It is an amazing work. I have already set up the environment but could not find the model data in the repository. Could you please upload the link to the "octree.bin, metadata.json, and output.json" files? Thanks!

**Comment by jdtsui** [comment]
Hi, 
We have released a sample, which you can access at the following link: https://drive.google.com/drive/folders/1WWHpzkRPYfVuqx9wP1wMpUM78LK3GlTk?usp=sharing
